version: "3.8"

services:
  postgres:
    image: postgres:13.1
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: backend_user,backend_support,backend_catalog
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://${HOST_IP}:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend-user:
    build: ./apps/backend-user
    ports:
      - 9191:8081
    environment:
      NODE_ENV: development
      POSTGRES_DB: backend_user
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  backend-support:
    build: ./apps/backend-support
    ports:
      - 9192:8081
    environment:
      NODE_ENV: development
      POSTGRES_DB: backend_support
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  backend-catalog:
    build: ./apps/backend-catalog
    ports:
      - 9193:8081
    environment:
      NODE_ENV: development
      POSTGRES_DB: backend_catalog
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
