version: "3.8"

services:
  postgres:
    image: postgres:13.1
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: backend_user,backend_user_test
